version: '3.8'

services:
  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_DB: "javarabbit"
      POSTGRES_USER: "backend"
      POSTGRES_PASSWORD: "backend123"
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
